# Generated by Django 5.1.7 on 2026-02-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
